#define JPATH_ANDROID_MOBILE_SURFACE_VIEW "com/techsoft3d/hps/virtual_training/AndroidMobileSurfaceView"
#define JPATH_ANDROID_USER_MOBILE_SURFACE_VIEW "com/techsoft3d/hps/virtual_training/AndroidUserMobileSurfaceView"
#define JPATH_MOBILE_APP "com/techsoft3d/hps/virtual_training/MobileApp"